const express = require('express')
const app = express()
const PORT = 3002
const cors = require('cors')

app.use(cors())

const bestNewMusicWomen = [
    {
        "title": 'nothing to declare',
        "artist": "700 bliss",
        "genre": "experimental, rap, electronic",
        "score": 8.3,
        "releaseDate": '2022-05-27',
        "bestNewTrackAwarded": false,
    },
    {
        'title': "hypnos",
        "artist": "ravyn lenae",
        "genre": "pop/r&b",
        "score": 8.5,
        "releaseDate": '2022-05-20',
        "bestNewTrackAwarded": false,
    },
    {
        'title': "topical dancer",
        "artist": "charlotte adigery, bolis pupul",
        "genre": "electronic",
        "score": 8.2,
        "releaseDate": '2022-03-04',
        "bestNewTrackAwarded": true,
    },
    {
        'title': "life on earth",
        "artist": "Hurray for the Riff Raff",
        "genre": "rock",
        "score": 8.3,
        "releaseDate": '2022-02-18',
        "bestNewTrackAwarded": false,
    },
    {
        "title": "heaux tales, mo' tales: the deluxe",
        "artist": "jazmine sullivan",
        "genre": "pop/r&b",
        "score": 8.4,
        "releaseDate": '2022-02-11',
        "bestNewTrackAwarded": false,
    },
    {
        'title': 'glitch princess',
        "artist": "yeule",
        "genre": "pop/r&b",
        "score": 8.3,
        "releaseDate": '2022-02-04',
        "bestNewTrackAwarded": true,
    },
    {
        'title': 'kick iii',
        "artist": "arca",
        "genre": "experimental",
        "score": 8.3,
        "releaseDate": '2021-12-01',
        "bestNewTrackAwarded": false,
    },
    {
        "title": 'una rosa',
        "artist": "xenia rubinos",
        "genre": "rock",
        "score": 8.4,
        "releaseDate": '2021-10-15',
        "bestNewTrackAwarded": false,
    },
    {
        "title": 'space 1.8',
        "artist": "nala sinephro",
        "genre": "jazz, experimental",
        "score": 8.3,
        "releaseDate": '2021-09-03',
        "bestNewTrackAwarded": false,
    },
    {
        "title": 'any shape you take',
        "artist": "indigo de souza",
        "genre": "rock",
        "score": 8.3,
        "releaseDate": '2021-08-27',
        "bestNewTrackAwarded": true,
    },
    {
        "title": 'fatigue',
        "artist": "l'rain",
        "genre": "experimental",
        "score": 8.5,
        "releaseDate": '2021-06-25',
        "bestNewTrackAwarded": false,
    },
    {
        "title": 'vulture prince',
        "artist": "arooj aftab",
        "genre": "jazz, folk/country",
        "score": 8.3,
        "releaseDate": '2021-04-23',
        "bestNewTrackAwarded": true,
    },
    {
        "title": 'uneasy',
        "artist": "vijay iyer, linda may han oh, tyshawn sorey",
        "genre": "jazz",
        "score": 8.6,
        "releaseDate": '2021-04-09',
        "bestNewTrackAwarded": false,
    },
    {
        'title': 'entertainment, death',
        "artist": "spirit of the beehive",
        "genre": "rock",
        "score": 8.3,
        "releaseDate": '2021-04-09',
        "bestNewTrackAwarded": false,
    },
    {
        'title': 'heaux tales',
        "artist": "jazmine sullivan",
        "genre": "pop/r&b",
        "score": 8.6,
        "releaseDate": '2021-01-08',
        "bestNewTrackAwarded": true,
    },
    {
        'title': "the angel you don't know",
        "artist": "amaarae",
        "genre": "pop/r&b",
        "score": 8.4,
        "releaseDate": '2020-11-13',
        "bestNewTrackAwarded": false,
    },
    {
        'title': 'live',
        "artist": "angel bat dawid, the brotherhood",
        "genre": "jazz",
        "score": 8.4,
        "releaseDate": '2020-10-31',
        "bestNewTrackAwarded": false,
    },
    {
        'title': 'mama, you can bet!',
        "artist": "jyoti",
        "genre": "jazz",
        "score": 8.4,
        "releaseDate": '2020-08-28',
        "bestNewTrackAwarded": false,
    },
    {
        'title': 'source',
        'artist': ' nubya garcia',
        "genre": "jazz",
        "score": 8.3,
        "releaseDate": '2020-08-21',
        "bestNewTrackAwarded": false,
    },
    {
        'title': 'the passion of',
        'artist': 'special interest',
        "genre": "rock",
        "score": 8.4,
        "releaseDate": '2020-06-19',
        "bestNewTrackAwarded": true,
    },
    {
        'title': 'foverver, ya girl',
        'artist': 'keiyaa',
        "genre": "pop/r&b",
        "score": 8.2,
        "releaseDate": '2020-03-27',
        "bestNewTrackAwarded": false,
    },
    {
        'title': 'magdelene',
        'artist': 'fka twigs',
        "genre": "electronic, pop/r&b",
        "score": 9.4,
        "releaseDate": '2019-11-08',
        "bestNewTrackAwarded": true,
    },
    {
        'title': 'jaime',
        'artist': 'brittany howard',
        "genre": "rock",
        "score": 8.6,
        "releaseDate": '2019-09-20',
        "bestNewTrackAwarded": false,
    },
    {
        'title': 'patience',
        'artist': 'mannequin pussy',
        "genre": "rock",
        "score": 8.4,
        "releaseDate": '2019-06-21',
        "bestNewTrackAwarded": true,
    },
    {
        'title': 'legacy! legacy!',
        'artist': 'jamila woods',
        "genre": "pop/r&b",
        "score": 8.4,
        "releaseDate": '2019-05-10',
        "bestNewTrackAwarded": true,
    },
    {
        'title': 'homecoming: the live album',
        'artist': 'beyonce',
        "genre": "pop/r&b",
        "score": 9.3,
        "releaseDate": '2019-04-17',
        "bestNewTrackAwarded": true,
    },
    {
        'title': 'punk',
        'artist': 'chai',
        "genre": "rock",
        "score": 8.3,
        "releaseDate": '2019-02-13',
        "bestNewTrackAwarded": false,
    },
    {
        'title': 'when i get home',
        'artist': 'solange',
        "genre": "pop/r&b",
        "score": 8.4,
        "releaseDate": '2019-03-01',
        "bestNewTrackAwarded": true,
    },
    {
        'title': 'room 25',
        'artist': 'noname',
        "genre": "rap",
        "score": 8.6,
        "releaseDate": '2018-09-18',
        "bestNewTrackAwarded": true,
    },
    {
        'title': 'be the cowboy',
        'artist': 'mitski',
        "genre": "rock",
        "score": 8.8,
        "releaseDate": '2018-08-17',
        "bestNewTrackAwarded": true,
    },
    {
        'title': 'hive mind',
        'artist': 'the internet',
        "genre": "pop/r&b",
        "score": 8.3,
        "releaseDate": '2018-07-20',
        "bestNewTrackAwarded": false,
    },
    {
        'title': 'everything is love',
        'artist': 'beyonce, jay-z',
        "genre": "pop/r&b/rap",
        "score": 8.2,
        "releaseDate": '2018-06-18',
        "bestNewTrackAwarded": true,
    },
    {
        'title': 'whack world',
        'artist': 'tierra whack',
        "genre": "rap",
        "score": 8.3,
        "releaseDate": '2018-05-30',
        "bestNewTrackAwarded": false,
    },
    {
        'title': 'isolation',
        'artist': 'kali uchis',
        "genre": "pop/r&b",
        "score": 8.6,
        "releaseDate": '2018-04-06',
        "bestNewTrackAwarded": true,
    },
    {
        'title': 'invasion of privacy',
        'artist': 'cardi b',
        "genre": "rap",
        "score": 8.7,
        "releaseDate": '2018-04-06',
        "bestNewTrackAwarded": true,
    },
    {
        'title': "everything's fine",
        'artist': 'jean grae, quelle chris',
        "genre": "rap",
        "score": 8.4,
        "releaseDate": '2018-03-30',
        "bestNewTrackAwarded": false,
    },
    {
        'title': 'ephorize',
        'artist': 'cupcakke',
        "genre": "rap",
        "score": 8.3,
        "releaseDate": '2018-01-05',
        "bestNewTrackAwarded": true,
    },
    {
        'title': 'take me apart',
        'artist': 'kelela',
        "genre": "pop/r&b",
        "score": 8.6,
        "releaseDate": '2017-10-06',
        "bestNewTrackAwarded": true,
    },
    {
        'title': 'ash',
        'artist': 'ibeyi',
        "genre": "pop/r&b",
        "score": 8.3,
        "releaseDate": '2017-09-27',
        "bestNewTrackAwarded": false,
    },
    {
        'title': 'ctrl',
        'artist': 'sza',
        "genre": "pop/r&b",
        "score": 8.4,
        "releaseDate": '2017-06-09',
        "bestNewTrackAwarded": false,
    },
    {
        'title': 'black origami',
        'artist': 'jlin',
        "genre": "electronic",
        "score": 8.8,
        "releaseDate": '2017-05-11',
        "bestNewTrackAwarded": true,
    },
    {
        'title': 'arca',
        'artist': 'arca',
        "genre": "experimental",
        "score": 8.5,
        "releaseDate": '2017-04-07',
        "bestNewTrackAwarded": true,
    },
    {
        'title': 'mono no aware',
        'artist': 'various artists',
        "genre": "",
        "score": 8.6,
        "releaseDate": '2017-03-17',
        "bestNewTrackAwarded": true,
    },
    {
        'title': 'everybody works',
        'artist': 'jay som',
        "genre": "rock",
        "score": 8.6,
        "releaseDate": '2017-03-10',
        "bestNewTrackAwarded": true,
    },
    {
        'title': 'infinite worlds',
        'artist': 'vagabon',
        "genre": "rock",
        "score": 8.5,
        "releaseDate": '2017-02-24',
        "bestNewTrackAwarded": true,
    },
    {
        'title': 'a seat at the table',
        'artist': 'solange',
        "genre": "pop/r&b",
        "score": 8.7,
        "releaseDate": '2016-09-30',
        "bestNewTrackAwarded": true,
    },
    {
        'title': 'a mulher do fim do mundo (a woman at the end of the world)',
        'artist': 'elza soares',
        "genre": "global",
        "score": 8.4,
        "releaseDate": '2016-10-03',
        "bestNewTrackAwarded": true,
    },
    {
        'title': 'heavn',
        'artist': 'jamila woods',
        "genre": "rpr/r&b",
        "score": 8.4,
        "releaseDate": '2016-07-17',
        "bestNewTrackAwarded": true,
    },
    {
        'title': 'puberty 2',
        'artist': 'mitski',
        "genre": "rock",
        "score": 8.5,
        "releaseDate": '2016-07-17',
        "bestNewTrackAwarded": true,
    },
    {
        'title': 'lemonade',
        'artist': 'beyonce',
        "genre": "pop/r&b",
        "score": 8.5,
        "releaseDate": '2016-04-23',
        "bestNewTrackAwarded": true,
    },
    {
        'title': 'a good night in the ghetto',
        'artist': 'kamaiyah',
        "genre": "rap",
        "score": 8.2,
        "releaseDate": '2016-03-14',
        "bestNewTrackAwarded": true,
    }, {
        'title': "emily's d+evolution",
        'artist': 'esperanza spalding',
        "genre": "jazz",
        "score": 8.6,
        "releaseDate": '2016-03-04',
        "bestNewTrackAwarded": true,
    },
    {
        'title': 'hallucinogen ep',
        'artist': 'kelela',
        "genre": "pop/r&b",
        "score": 8.3,
        "releaseDate": '2015-10-09',
        "bestNewTrackAwarded": false,
    },
    {
        'title': 'me',
        'artist': 'empress of',
        "genre": "pop/r&b",
        "score": 8.2,
        "releaseDate": '2015-09-11',
        "bestNewTrackAwarded": true,
    },
    {
        'title': 'm3l155x',
        'artist': 'fka twigs',
        "genre": "pop/r&b, electronic",
        "score": 8.6,
        "releaseDate": '2015-08-13',
        "bestNewTrackAwarded": true,
    },
    {
        'title': 'february 15 ep',
        'artist': 'nao',
        "genre": "pop/r&b",
        "score": 8.4,
        "releaseDate": '2015-05-01',
        "bestNewTrackAwarded": true,
    },
    {
        'title': 'dark energy',
        'artist': 'jlin',
        "genre": "electronic",
        "score": 8.5,
        "releaseDate": '2015-03-25',
        "bestNewTrackAwarded": true,
    }
]

app.get('/', (req, res) => {
    res.sendFile(__dirname + '/index.html')
})

app.get('/api/', (req, res) => {
    res.json(bestNewMusicWomen)
})

app.listen(process.env.PORT || PORT, () => {
    console.log(`we out here on this server`)
})